#!name=Alight Motion
#!desc=Unlock Alight Motion Premium
# 💬 Web: https://beacons.ai/manhyen  
# 🚀 Released by: Khổng Mạnh Yên

[General]
bypass-system = true
skip-proxy = *.local, *.crashlytics.com
tun-excluded-routes = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12

[MITM]
hostname = api.revenuecat.com, buy.itunes.apple.com, us-central1-alight-creative.cloudfunctions.net

[Script]
http-response https://us-central1-alight-creative.cloudfunctions.net/getAccountStatusAndLicenses script-path=https://raw.githubusercontent.com/manhyen/kthy/refs/heads/main/Script/AlightMotion.js, requires-body=true, timeout=5, tag=Alight Motion

#!author=Khổng Mạnh Yên
