#!name=🐾 Picsart Premium - Yên Simp Lỏ
#!desc=Unlock Picsart Premium by KHỔNG MẠNH YÊN, Mở khóa Pro cho PicArt
#!author= Mạnh Yên (Kthy) 
# 💬 Web: https://beacons.ai/manhyen  
# 🚀 Tạo bởi: Khổng Mạnh Yên  
#!version=1.1

[MITM]
hostname = api.revenuecat.com,buy.itunes.apple.com,api.picsart.com, subscription.picsart.com

[Script]
# API chính của Picsart (iOS + Android)
http-response ^https:\/\/api\.picsart\.com\/subscriptions\/?.* requires-body=1, timeout=10, script-path=https://raw.githubusercontent.com/manhyen/kthy/refs/heads/main/Script/PicArt.js, tag=🐾 Picsart Premium

# Endpoint phụ (app gọi ngẫu nhiên)
http-response ^https:\/\/subscription\.picsart\.com\/api\/v\d\/subscriptions\/?.* requires-body=1, timeout=10, script-path=https://raw.githubusercontent.com/manhyen/kthy/refs/heads/main/Script/PicArt.js, tag=🐾 Picsart Premium
