#!name=YouTube Premium 2025 - YenVer2
#!desc=Chặn quảng cáo YouTube + Music | Hỗ trợ PiP, phụ đề & phát nền | Yêu cầu bật bảo vệ QUIC
#!tag=Chặn quảng cáo, YouTube, Music, PiP
#!url=https://www.facebook.com/share/1PqvWcnWd4/
# 👤 Author: : Khổng Mạnh Yên
# 💬 Discord: https://discord.gg/juY9tw5AJY  
# 🚀 Released by: Yenver2  
#!icon = https://i.ibb.co/bjJLDjcT/5b2b03676b839898f3de9ba2b0556789.jpg


[Rule]
AND,((DOMAIN-SUFFIX,googlevideo.com), (PROTOCOL,UDP)),REJECT
AND,((DOMAIN,youtubei.googleapis.com), (PROTOCOL,UDP)),REJECT

[Map Local]
^https?:\/\/[\w-]+\.googlevideo\.com\/initplayback.+&oad data-type=text data="" status-code=200

[Script]
YouTube响应 = type=http-response,pattern=^https:\/\/youtubei\.googleapis\.com\/(youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting|get_watch))(\?(.*))?$,requires-body=1,max-size=-1,binary-body-mode=1,script-path=https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Youtube/youtube.response.js,argument="{"lyricLang":"{{{歌词翻译语言}}}","captionLang":"{{{字幕翻译语言}}}","blockUpload":{{{屏蔽上传按钮}}},"blockImmersive":{{{屏蔽选段按钮}}},"blockShorts":{{{屏蔽Shorts按钮}}},"debug":{{{启用调试模式}}}}"

[MITM]
hostname = %APPEND% youtu.be, *.googlevideo.com, youtubei.googleapis.com
