#!name= 🐾YouTube Premium 2025 - Yen No Simp🐣
#!desc=Chặn quảng cáo YouTube + Music | Hỗ trợ PiP, phụ đề & phát nền | Yêu cầu bật bảo vệ QUIC
#!tag=Chặn quảng cáo, YouTube, Music, PiP
#!url=https://www.facebook.com/yenv2
#!👤 author= Mạnh Yên (Kthy)
# 💬 Telegram: https://t.me/yennosimp  
# 👑 Tạo bởi: yennosimp  
#!icon = https://i.ibb.co/bjJLDjcT/5b2b03676b839898f3de9ba2b0556789.jpg


[Rule]
AND,((DOMAIN-SUFFIX,googlevideo.com), (PROTOCOL,UDP)),REJECT
AND,((DOMAIN,youtubei.googleapis.com), (PROTOCOL,UDP)),REJECT

[Map Local]
^https?:\/\/[\w-]+\.googlevideo\.com\/initplayback.+&oad data-type=text data="" status-code=200

[Script]
//# 🚫 Xin Đừng chỉnh sửa bất cứ thứ j ở đây
YouTube响应 = type=http-response,pattern=^https:\/\/youtubei\.googleapis\.com\/(youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting|get_watch))(\?(.*))?$,requires-body=1,max-size=-1,binary-body-mode=1,script-path=https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Youtube/youtube.response.js,argument="{"lyricLang":"{{{歌词翻译语言}}}","captionLang":"{{{字幕翻译语言}}}","blockUpload":{{{屏蔽上传按钮}}},"blockImmersive":{{{屏蔽选段按钮}}},"blockShorts":{{{屏蔽Shorts按钮}}},"debug":{{{启用调试模式}}}}"

[MITM]
//# 🍃Module này mình tự tìm hiểu và lm ra xin đừng ăn cắp😮‍💨
hostname = %APPEND% youtu.be, *.googlevideo.com, youtubei.googleapis.com
